
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: desafiofinal_3h1y
  username: desafiofinal
  password: uqglJXXP2USyKripK2hr7ZsSZEZtlJos
  host: postgres://desafiofinal:uqglJXXP2USyKripK2hr7ZsSZEZtlJos@dpg-ciiukjdgkuvhnnacmlhg-a/desafiofinal_3h1y
  port: 5432

production:
  <<: *default
 url: <%= ENV['DATABASE_URL'] %>
